# Application Configuration
spring.application.name=${SPRING_APPLICATION_NAME:Finavex}
server.port=8080

# JPA Configuration
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}

# Session Configuration
spring.session.store-type=${SPRING_SESSION_STORE_TYPE:jdbc}
spring.session.jdbc.initialize-schema=${SPRING_SESSION_JDBC_INITIALIZE_SCHEMA:always}

# Logging
logging.level.root=${LOGGING_LEVEL_ROOT:INFO}
logging.level.com.semillero.Ibero.Finavex=${LOGGING_LEVEL_COM_SEMILLERO_IBERO_FINAVEX:DEBUG}

# Profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

