# Database Configuration for Dev Profile - OPTIONAL
# If not provided, app runs WITHOUT database functionality
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false  # Desactivado en dev - Hibernate maneja el schema con create-drop

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    from: ${MAIL_USERNAME_SEND}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
ai:
  timeout:
    execution: 40s

sentry:
  dsn: ${SENTRY_DSN}
  send-default-pii: true
  environment: development
  enabled: true
  traces-sample-rate: 1.0
