name: push to main from front

on: 
  push:
    branches:
      - front

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: config git
        run: |
          git config user.name "merge BOT"
          git config user.email "merge@gmail.com"

      - name: merge
        run: |
          git checkout main
          git merge front -X theirs --no-edit
          git push origin main
